services:
  traefik:
    image: traefik:latest
    restart: unless-stopped
    command:
      - --api.dashboard=true
      - --api.debug=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.file.directory=/config
      - --providers.file.watch=true
      - --log.level=TRACE
      - --accesslog=true
      - --log.maxsize=1
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      # Development mode
      - --experimental.localPlugins.swagger-merge.moduleName=github.com/Vocovo/traefik-swagger-merge
      # Production mode
      # - --experimental.plugins.swagger-merge.modulename=github.com/Vocovo/traefik-swagger-merge
      # - --experimental.plugins.swagger-merge.version=v0.1.11
    ports:
      - "8080:80"    # Balancer port
      - "8090:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/plugins-local/src/github.com/Vocovo/traefik-swagger-merge
      - ./swagger-merge-config.yaml:/config/swagger-merge-config.yaml

  service1:
    build:
      context: .
      dockerfile: ./tests/Dockerfile
    env_file:
      - .env
    volumes:
      - ./tests/8081.yaml:/home/static/swagger.yaml
      - ./tests/index.html:/home/static/index.html
      - ./tests/feature1.json:/home/static/api/v1/feature1/index.html
    ports:
      - "${HTTP_PORT1:-8081}:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.feature1.rule=PathPrefix(`/api/v1/feature1`)"
      - "traefik.http.routers.feature1.entrypoints=web"

  service2:
    build:
      context: .
      dockerfile: ./tests/Dockerfile
    env_file:
      - .env
    volumes:
      - ./tests/8082.yaml:/home/static/swagger.yaml
      - ./tests/index.html:/home/static/index.html
      - ./tests/feature2.json:/home/static/api/v1/feature2/index.html
    ports:
      - "${HTTP_PORT2:-8082}:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.feature2.rule=PathPrefix(`/api/v1/feature2`)"
      - "traefik.http.routers.feature2.entrypoints=web"

  service3:
    build:
      context: .
      dockerfile: ./tests/Dockerfile
    env_file:
      - .env
    volumes:
      - ./tests/8083.yaml:/home/static/swagger.yaml
      - ./tests/index.html:/home/static/index.html
      - ./tests/feature3.json:/home/static/api/v1/feature3/index.html
    ports:
      - "${HTTP_PORT3:-8083}:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.feature3.rule=PathPrefix(`/api/v1/feature3`)"
      - "traefik.http.routers.feature3.entrypoints=web"

  whoami:
    image: traefik/whoami
